[tool.poetry]
name = "tictactournament"
version = "0.1.0"
description = ""
authors = ["MatDebLund <ma8308de-s@student.lu.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
